import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { MapPin, Plus, Trash2, Edit, Check } from 'lucide-react';
import { useGetLakeLocationEvents, useCreateLakeLocationEvent, useUpdateLakeLocationEvent, useDeleteLakeLocationEvent, useGetCampers } from '../hooks/useQueries';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import { LakeLocationEvent, LakeLocation } from '../backend';
import { toast } from 'sonner';

// Map display names to enum values
const LOCATION_OPTIONS = [
  { display: 'Marina', value: LakeLocation.marina },
  { display: 'Big Island Beach', value: LakeLocation.bigIslandBeach },
  { display: 'Big Island Cove', value: LakeLocation.bigIslandCove },
  { display: 'Sand Bar', value: LakeLocation.sandBar },
  { display: 'Karen Cove', value: LakeLocation.karenCove },
  { display: 'Sandy Beach', value: LakeLocation.sandyBeach },
  { display: 'Skyline Bar', value: LakeLocation.skylineBar },
];

// Map enum values to display names
const getLocationDisplayName = (location: LakeLocation): string => {
  const option = LOCATION_OPTIONS.find(opt => opt.value === location);
  return option?.display || location;
};

export default function LakeLocationSection() {
  const { identity } = useInternetIdentity();
  const { data: events = [], isLoading: eventsLoading } = useGetLakeLocationEvents();
  const { data: campers } = useGetCampers();
  const createEvent = useCreateLakeLocationEvent();
  const updateEvent = useUpdateLakeLocationEvent();
  const deleteEvent = useDeleteLakeLocationEvent();

  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [editingEvent, setEditingEvent] = useState<LakeLocationEvent | null>(null);
  const [eventTime, setEventTime] = useState('');
  const [selectedLocation, setSelectedLocation] = useState<LakeLocation | ''>('');
  const [senderName, setSenderName] = useState('');

  // Load sender name from localStorage (same as CampfireSection)
  useEffect(() => {
    const savedName = localStorage.getItem('camperName');
    if (savedName) {
      setSenderName(savedName);
    }
  }, []);

  // Find current camper data
  const currentCamper = campers?.find(camper => camper.name === senderName);

  const resetForm = () => {
    setEventTime('');
    setSelectedLocation('');
  };

  const handleCreateEvent = async () => {
    if (!senderName) {
      toast.error('Please set up your profile first');
      return;
    }

    if (!eventTime || !selectedLocation) {
      toast.error('Please fill in all fields');
      return;
    }

    try {
      await createEvent.mutateAsync({
        organizer: senderName,
        time: eventTime,
        location: selectedLocation,
      });
      
      setIsCreateDialogOpen(false);
      resetForm();
      toast.success('Lake location event created successfully!');
    } catch (error) {
      console.error('Error creating event:', error);
      toast.error('Failed to create event');
    }
  };

  const handleEditEvent = (event: LakeLocationEvent) => {
    setEditingEvent(event);
    setEventTime(event.time);
    setSelectedLocation(event.location);
    setIsEditDialogOpen(true);
  };

  const handleUpdateEvent = async () => {
    if (!editingEvent || !senderName) return;

    if (!eventTime || !selectedLocation) {
      toast.error('Please fill in all fields');
      return;
    }

    try {
      await updateEvent.mutateAsync({
        organizer: editingEvent.organizer,
        time: eventTime,
        location: selectedLocation,
      });
      
      setIsEditDialogOpen(false);
      setEditingEvent(null);
      resetForm();
      toast.success('Lake location event updated successfully!');
    } catch (error) {
      console.error('Error updating event:', error);
      toast.error('Failed to update event');
    }
  };

  const handleDeleteEvent = async (event: LakeLocationEvent) => {
    try {
      // Use the event ID that was generated by the backend
      await deleteEvent.mutateAsync(event.id);
      toast.success('Lake location event deleted successfully!');
    } catch (error: any) {
      console.error('Error deleting event:', error);
      
      // Provide user-friendly error message
      const errorMessage = error?.message || '';
      if (errorMessage.includes('not found') || errorMessage.includes('Lake location event not found')) {
        toast.error('Event not found. It may have already been deleted.');
      } else {
        toast.error('Failed to delete event. Please try again.');
      }
    }
  };

  const formatEventTime = (time: string) => {
    const [hours, minutes] = time.split(':');
    const hour = parseInt(hours);
    const ampm = hour >= 12 ? 'PM' : 'AM';
    const displayHour = hour % 12 || 12;
    return `${displayHour}:${minutes} ${ampm}`;
  };

  const canEditEvent = (event: LakeLocationEvent): boolean => {
    return !!identity && event.owner.toString() === identity.getPrincipal().toString();
  };

  const LocationSelector = ({ value, onChange }: { value: LakeLocation | ''; onChange: (value: LakeLocation) => void }) => (
    <div className="space-y-3">
      <Label className="text-base font-medium">Choose Location</Label>
      <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
        {LOCATION_OPTIONS.map((option) => (
          <Button
            key={option.value}
            type="button"
            variant={value === option.value ? "default" : "outline"}
            size="sm"
            onClick={() => onChange(option.value)}
            className={`relative h-10 text-sm font-medium transition-all duration-200 ${
              value === option.value 
                ? "bg-blue-600 hover:bg-blue-700 text-white shadow-md ring-2 ring-blue-200 dark:ring-blue-800" 
                : "hover:bg-blue-50 dark:hover:bg-blue-900/20 hover:border-blue-300 dark:hover:border-blue-700"
            }`}
          >
            <span className="flex items-center justify-center gap-2">
              {value === option.value && <Check className="w-3 h-3" />}
              {option.display}
            </span>
          </Button>
        ))}
      </div>
    </div>
  );

  if (!senderName) {
    return (
      <div className="space-y-6">
        <div className="text-center">
          <h1 className="text-3xl font-bold mb-2">Lake Locations</h1>
          <p className="text-muted-foreground">
            Please let the group know where you are hanging out at
          </p>
        </div>

        <Card>
          <CardHeader className="text-center">
            <div className="mx-auto w-16 h-16 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center mb-4">
              <MapPin className="w-8 h-8 text-blue-600 dark:text-blue-400" />
            </div>
            <CardTitle>Profile Setup Required</CardTitle>
          </CardHeader>
          <CardContent className="text-center">
            <p className="text-muted-foreground">
              Please set up your profile in the Profile section to create and manage lake location events.
            </p>
          </CardContent>
        </Card>

        {/* Still show existing events even if user hasn't set up profile */}
        <div className="space-y-4">
          {eventsLoading ? (
            <Card>
              <CardContent className="p-6 text-center">
                <p className="text-muted-foreground">Loading events...</p>
              </CardContent>
            </Card>
          ) : events.length === 0 ? (
            <Card>
              <CardContent className="p-6 text-center">
                <div className="mx-auto w-16 h-16 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center mb-4">
                  <MapPin className="w-8 h-8 text-blue-600 dark:text-blue-400" />
                </div>
                <p className="text-muted-foreground">
                  No lake location events scheduled yet. Set up your profile to create the first one!
                </p>
              </CardContent>
            </Card>
          ) : (
            events.map((event) => (
              <Card key={event.id} className="border-l-4 border-l-blue-500">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="flex items-center space-x-3">
                      <div className="w-10 h-10 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center">
                        <MapPin className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                      </div>
                      <div>
                        <CardTitle className="text-lg">{getLocationDisplayName(event.location)}</CardTitle>
                        <p className="text-sm text-muted-foreground">
                          Organized by {event.organizer}
                        </p>
                      </div>
                    </div>
                    <div className="flex space-x-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleDeleteEvent(event)}
                        disabled={deleteEvent.isPending}
                        className="text-destructive hover:text-destructive hover:bg-destructive/10"
                        title="Delete event"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                    <span>🕐</span>
                    <span>{formatEventTime(event.time)}</span>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h1 className="text-3xl font-bold mb-2">Lake Locations</h1>
        <p className="text-muted-foreground">
          Please let the group know where you are hanging out at
        </p>
      </div>

      <div className="flex justify-center">
        <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
          <DialogTrigger asChild>
            <Button className="bg-blue-600 hover:bg-blue-700 text-white" onClick={resetForm}>
              <Plus className="w-4 h-4 mr-2" />
              Create Lake Location Event
            </Button>
          </DialogTrigger>
          <DialogContent className="bg-background/95 backdrop-blur-sm border border-border/50 max-w-lg max-h-[90vh] flex flex-col">
            <DialogHeader className="shrink-0">
              <DialogTitle>Create Lake Location Event</DialogTitle>
            </DialogHeader>
            <ScrollArea className="flex-1 pr-4">
              <div className="space-y-6 pb-4">
                <div>
                  <Label htmlFor="event-time" className="text-base font-medium">Time</Label>
                  <Input
                    id="event-time"
                    type="time"
                    value={eventTime}
                    onChange={(e) => setEventTime(e.target.value)}
                    className="mt-2"
                  />
                </div>
                <LocationSelector value={selectedLocation} onChange={setSelectedLocation} />
              </div>
            </ScrollArea>
            <div className="flex justify-end space-x-3 pt-4 border-t shrink-0">
              <Button
                variant="outline"
                onClick={() => {
                  setIsCreateDialogOpen(false);
                  resetForm();
                }}
              >
                Cancel
              </Button>
              <Button
                onClick={handleCreateEvent}
                disabled={createEvent.isPending || !eventTime || !selectedLocation}
                className="bg-blue-600 hover:bg-blue-700 text-white"
              >
                {createEvent.isPending ? 'Creating...' : 'Create Event'}
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="bg-background/95 backdrop-blur-sm border border-border/50 max-w-lg max-h-[90vh] flex flex-col">
          <DialogHeader className="shrink-0">
            <DialogTitle>Edit Lake Location Event</DialogTitle>
          </DialogHeader>
          <ScrollArea className="flex-1 pr-4">
            <div className="space-y-6 pb-4">
              <div>
                <Label htmlFor="edit-event-time" className="text-base font-medium">Time</Label>
                <Input
                  id="edit-event-time"
                  type="time"
                  value={eventTime}
                  onChange={(e) => setEventTime(e.target.value)}
                  className="mt-2"
                />
              </div>
              <LocationSelector value={selectedLocation} onChange={setSelectedLocation} />
            </div>
          </ScrollArea>
          <div className="flex justify-end space-x-3 pt-4 border-t shrink-0">
            <Button
              variant="outline"
              onClick={() => {
                setIsEditDialogOpen(false);
                setEditingEvent(null);
                resetForm();
              }}
            >
              Cancel
            </Button>
            <Button
              onClick={handleUpdateEvent}
              disabled={updateEvent.isPending || !eventTime || !selectedLocation}
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              {updateEvent.isPending ? 'Updating...' : 'Update Event'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      <div className="space-y-4">
        {eventsLoading ? (
          <Card>
            <CardContent className="p-6 text-center">
              <p className="text-muted-foreground">Loading events...</p>
            </CardContent>
          </Card>
        ) : events.length === 0 ? (
          <Card>
            <CardContent className="p-6 text-center">
              <div className="mx-auto w-16 h-16 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center mb-4">
                <MapPin className="w-8 h-8 text-blue-600 dark:text-blue-400" />
              </div>
              <p className="text-muted-foreground">
                No lake location events scheduled yet. Create the first one!
              </p>
            </CardContent>
          </Card>
        ) : (
          events.map((event) => (
            <Card key={event.id} className="border-l-4 border-l-blue-500">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="flex items-center space-x-3">
                    <div className="w-10 h-10 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center">
                      <MapPin className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                    </div>
                    <div>
                      <CardTitle className="text-lg">{getLocationDisplayName(event.location)}</CardTitle>
                      <p className="text-sm text-muted-foreground">
                        Organized by {event.organizer}
                      </p>
                    </div>
                  </div>
                  <div className="flex space-x-2">
                    {canEditEvent(event) && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleEditEvent(event)}
                        disabled={updateEvent.isPending}
                        title="Edit event"
                      >
                        <Edit className="w-4 h-4" />
                      </Button>
                    )}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDeleteEvent(event)}
                      disabled={deleteEvent.isPending}
                      className="text-destructive hover:text-destructive hover:bg-destructive/10"
                      title="Delete event"
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                  <span>🕐</span>
                  <span>{formatEventTime(event.time)}</span>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
