/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NotificationPreferences {
    appearance: ToastAppearance;
    triggers: NotificationTriggers;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LakeLocationEvent {
    id: string;
    organizer: string;
    owner: Principal;
    time: string;
    location: LakeLocation;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CampfireEvent {
    organizer: string;
    campsiteNumber: string;
    owner: Principal;
    date: bigint;
    time: string;
}
export interface Camper {
    status: ArrivalStatus;
    siteNumber?: string;
    plannedArrival?: bigint;
    name: string;
    plannedDeparture?: bigint;
    numberOfCampers: bigint;
}
export interface ToastAppearance {
    animation: string;
    style: string;
    position: string;
}
export interface Message {
    content: string;
    sender: string;
    timestamp: Time;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface NotificationTriggers {
    departureWarning: boolean;
    messageReceived: boolean;
    campfireInvitation: boolean;
    lakeArrivalAlert: boolean;
    lakeLocationUpdate: boolean;
    eventReminder: boolean;
}
export interface UserProfile {
    notificationPreferences?: NotificationPreferences;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ArrivalStatus {
    onTheWay = "onTheWay",
    atTheLake = "atTheLake",
    planning = "planning"
}
export enum LakeLocation {
    sandBar = "sandBar",
    karenCove = "karenCove",
    bigIslandBeach = "bigIslandBeach",
    skylineBar = "skylineBar",
    marina = "marina",
    bigIslandCove = "bigIslandCove",
    sandyBeach = "sandyBeach"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addOrUpdateCamper(name: string, plannedArrival: bigint | null, plannedDeparture: bigint | null, siteNumber: string | null, numberOfCampers: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCamper(name: string): Promise<void>;
    createCampfireEvent(organizer: string, date: bigint, time: string, campsiteNumber: string): Promise<void>;
    createLakeLocationEvent(organizer: string, time: string, location: LakeLocation): Promise<void>;
    deleteCampfireEvent(eventId: bigint): Promise<void>;
    deleteLakeLocationEvent(eventId: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    getCallerNotificationPreferences(): Promise<NotificationPreferences | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCampers(): Promise<Array<Camper>>;
    getCampfireEvents(): Promise<Array<CampfireEvent>>;
    getFileReference(path: string): Promise<FileReference>;
    getLakeLocationEvents(): Promise<Array<LakeLocationEvent>>;
    getMessages(): Promise<Array<Message>>;
    getUserNotificationPreferences(user: Principal): Promise<NotificationPreferences | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    registerFileReference(path: string, hash: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(sender: string, content: string): Promise<void>;
    updateCallerNotificationPreferences(preferences: NotificationPreferences): Promise<void>;
    updateCampfireEvent(organizer: string, date: bigint, time: string, campsiteNumber: string): Promise<void>;
    updateLakeLocationEvent(organizer: string, time: string, location: LakeLocation): Promise<void>;
    updateNumberOfCampers(name: string, numberOfCampers: bigint): Promise<void>;
    updatePlannedDeparture(name: string, plannedDeparture: bigint | null): Promise<void>;
    updateSiteNumber(name: string, siteNumber: string | null): Promise<void>;
    updateStatus(name: string, status: ArrivalStatus): Promise<void>;
}
import type { ArrivalStatus as _ArrivalStatus, Camper as _Camper, LakeLocation as _LakeLocation, LakeLocationEvent as _LakeLocationEvent, NotificationPreferences as _NotificationPreferences, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addOrUpdateCamper(arg0: string, arg1: bigint | null, arg2: bigint | null, arg3: string | null, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCamper(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCamper(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCamper(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCamper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCamper(arg0);
            return result;
        }
    }
    async createCampfireEvent(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampfireEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampfireEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createLakeLocationEvent(arg0: string, arg1: string, arg2: LakeLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLakeLocationEvent(arg0, arg1, to_candid_LakeLocation_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLakeLocationEvent(arg0, arg1, to_candid_LakeLocation_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteCampfireEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampfireEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampfireEvent(arg0);
            return result;
        }
    }
    async deleteLakeLocationEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLakeLocationEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLakeLocationEvent(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getCallerNotificationPreferences(): Promise<NotificationPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNotificationPreferences();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNotificationPreferences();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampers(): Promise<Array<Camper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampfireEvents(): Promise<Array<CampfireEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampfireEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampfireEvents();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getLakeLocationEvents(): Promise<Array<LakeLocationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLakeLocationEvents();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLakeLocationEvents();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getUserNotificationPreferences(arg0: Principal): Promise<NotificationPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotificationPreferences(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotificationPreferences(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateCallerNotificationPreferences(arg0: NotificationPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerNotificationPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerNotificationPreferences(arg0);
            return result;
        }
    }
    async updateCampfireEvent(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampfireEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampfireEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLakeLocationEvent(arg0: string, arg1: string, arg2: LakeLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLakeLocationEvent(arg0, arg1, to_candid_LakeLocation_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLakeLocationEvent(arg0, arg1, to_candid_LakeLocation_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateNumberOfCampers(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNumberOfCampers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNumberOfCampers(arg0, arg1);
            return result;
        }
    }
    async updatePlannedDeparture(arg0: string, arg1: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlannedDeparture(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlannedDeparture(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSiteNumber(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteNumber(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteNumber(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStatus(arg0: string, arg1: ArrivalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(arg0, to_candid_ArrivalStatus_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(arg0, to_candid_ArrivalStatus_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ArrivalStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArrivalStatus): ArrivalStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Camper_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Camper): Camper {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LakeLocationEvent_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LakeLocationEvent): LakeLocationEvent {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_LakeLocation_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LakeLocation): LakeLocation {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationPreferences]): NotificationPreferences | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationPreferences: [] | [_NotificationPreferences];
    name: string;
}): {
    notificationPreferences?: NotificationPreferences;
    name: string;
} {
    return {
        notificationPreferences: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.notificationPreferences)),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ArrivalStatus;
    siteNumber: [] | [string];
    plannedArrival: [] | [bigint];
    name: string;
    plannedDeparture: [] | [bigint];
    numberOfCampers: bigint;
}): {
    status: ArrivalStatus;
    siteNumber?: string;
    plannedArrival?: bigint;
    name: string;
    plannedDeparture?: bigint;
    numberOfCampers: bigint;
} {
    return {
        status: from_candid_ArrivalStatus_n23(_uploadFile, _downloadFile, value.status),
        siteNumber: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.siteNumber)),
        plannedArrival: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.plannedArrival)),
        name: value.name,
        plannedDeparture: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.plannedDeparture)),
        numberOfCampers: value.numberOfCampers
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    organizer: string;
    owner: Principal;
    time: string;
    location: _LakeLocation;
}): {
    id: string;
    organizer: string;
    owner: Principal;
    time: string;
    location: LakeLocation;
} {
    return {
        id: value.id,
        organizer: value.organizer,
        owner: value.owner,
        time: value.time,
        location: from_candid_LakeLocation_n30(_uploadFile, _downloadFile, value.location)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onTheWay: null;
} | {
    atTheLake: null;
} | {
    planning: null;
}): ArrivalStatus {
    return "onTheWay" in value ? ArrivalStatus.onTheWay : "atTheLake" in value ? ArrivalStatus.atTheLake : "planning" in value ? ArrivalStatus.planning : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sandBar: null;
} | {
    karenCove: null;
} | {
    bigIslandBeach: null;
} | {
    skylineBar: null;
} | {
    marina: null;
} | {
    bigIslandCove: null;
} | {
    sandyBeach: null;
}): LakeLocation {
    return "sandBar" in value ? LakeLocation.sandBar : "karenCove" in value ? LakeLocation.karenCove : "bigIslandBeach" in value ? LakeLocation.bigIslandBeach : "skylineBar" in value ? LakeLocation.skylineBar : "marina" in value ? LakeLocation.marina : "bigIslandCove" in value ? LakeLocation.bigIslandCove : "sandyBeach" in value ? LakeLocation.sandyBeach : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Camper>): Array<Camper> {
    return value.map((x)=>from_candid_Camper_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LakeLocationEvent>): Array<LakeLocationEvent> {
    return value.map((x)=>from_candid_LakeLocationEvent_n28(_uploadFile, _downloadFile, x));
}
function to_candid_ArrivalStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArrivalStatus): _ArrivalStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_LakeLocation_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LakeLocation): _LakeLocation {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationPreferences?: NotificationPreferences;
    name: string;
}): {
    notificationPreferences: [] | [_NotificationPreferences];
    name: string;
} {
    return {
        notificationPreferences: value.notificationPreferences ? candid_some(value.notificationPreferences) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LakeLocation): {
    sandBar: null;
} | {
    karenCove: null;
} | {
    bigIslandBeach: null;
} | {
    skylineBar: null;
} | {
    marina: null;
} | {
    bigIslandCove: null;
} | {
    sandyBeach: null;
} {
    return value == LakeLocation.sandBar ? {
        sandBar: null
    } : value == LakeLocation.karenCove ? {
        karenCove: null
    } : value == LakeLocation.bigIslandBeach ? {
        bigIslandBeach: null
    } : value == LakeLocation.skylineBar ? {
        skylineBar: null
    } : value == LakeLocation.marina ? {
        marina: null
    } : value == LakeLocation.bigIslandCove ? {
        bigIslandCove: null
    } : value == LakeLocation.sandyBeach ? {
        sandyBeach: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArrivalStatus): {
    onTheWay: null;
} | {
    atTheLake: null;
} | {
    planning: null;
} {
    return value == ArrivalStatus.onTheWay ? {
        onTheWay: null
    } : value == ArrivalStatus.atTheLake ? {
        atTheLake: null
    } : value == ArrivalStatus.planning ? {
        planning: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
