/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArrivalStatus = { 'onTheWay' : null } |
  { 'atTheLake' : null } |
  { 'planning' : null };
export interface Camper {
  'status' : ArrivalStatus,
  'siteNumber' : [] | [string],
  'plannedArrival' : [] | [bigint],
  'name' : string,
  'plannedDeparture' : [] | [bigint],
  'numberOfCampers' : bigint,
}
export interface CampfireEvent {
  'organizer' : string,
  'campsiteNumber' : string,
  'owner' : Principal,
  'date' : bigint,
  'time' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export type LakeLocation = { 'sandBar' : null } |
  { 'karenCove' : null } |
  { 'bigIslandBeach' : null } |
  { 'skylineBar' : null } |
  { 'marina' : null } |
  { 'bigIslandCove' : null } |
  { 'sandyBeach' : null };
export interface LakeLocationEvent {
  'id' : string,
  'organizer' : string,
  'owner' : Principal,
  'time' : string,
  'location' : LakeLocation,
}
export interface Message {
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
}
export interface NotificationPreferences {
  'appearance' : ToastAppearance,
  'triggers' : NotificationTriggers,
}
export interface NotificationTriggers {
  'departureWarning' : boolean,
  'messageReceived' : boolean,
  'campfireInvitation' : boolean,
  'lakeArrivalAlert' : boolean,
  'lakeLocationUpdate' : boolean,
  'eventReminder' : boolean,
}
export type Time = bigint;
export interface ToastAppearance {
  'animation' : string,
  'style' : string,
  'position' : string,
}
export interface UserProfile {
  'notificationPreferences' : [] | [NotificationPreferences],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addOrUpdateCamper' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string], bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCamper' : ActorMethod<[string], undefined>,
  'createCampfireEvent' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
  'createLakeLocationEvent' : ActorMethod<
    [string, string, LakeLocation],
    undefined
  >,
  'deleteCampfireEvent' : ActorMethod<[bigint], undefined>,
  'deleteLakeLocationEvent' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getCallerNotificationPreferences' : ActorMethod<
    [],
    [] | [NotificationPreferences]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampers' : ActorMethod<[], Array<Camper>>,
  'getCampfireEvents' : ActorMethod<[], Array<CampfireEvent>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getLakeLocationEvents' : ActorMethod<[], Array<LakeLocationEvent>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getUserNotificationPreferences' : ActorMethod<
    [Principal],
    [] | [NotificationPreferences]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'updateCallerNotificationPreferences' : ActorMethod<
    [NotificationPreferences],
    undefined
  >,
  'updateCampfireEvent' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
  'updateLakeLocationEvent' : ActorMethod<
    [string, string, LakeLocation],
    undefined
  >,
  'updateNumberOfCampers' : ActorMethod<[string, bigint], undefined>,
  'updatePlannedDeparture' : ActorMethod<[string, [] | [bigint]], undefined>,
  'updateSiteNumber' : ActorMethod<[string, [] | [string]], undefined>,
  'updateStatus' : ActorMethod<[string, ArrivalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];