/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LakeLocation = IDL.Variant({
  'sandBar' : IDL.Null,
  'karenCove' : IDL.Null,
  'bigIslandBeach' : IDL.Null,
  'skylineBar' : IDL.Null,
  'marina' : IDL.Null,
  'bigIslandCove' : IDL.Null,
  'sandyBeach' : IDL.Null,
});
export const ToastAppearance = IDL.Record({
  'animation' : IDL.Text,
  'style' : IDL.Text,
  'position' : IDL.Text,
});
export const NotificationTriggers = IDL.Record({
  'departureWarning' : IDL.Bool,
  'messageReceived' : IDL.Bool,
  'campfireInvitation' : IDL.Bool,
  'lakeArrivalAlert' : IDL.Bool,
  'lakeLocationUpdate' : IDL.Bool,
  'eventReminder' : IDL.Bool,
});
export const NotificationPreferences = IDL.Record({
  'appearance' : ToastAppearance,
  'triggers' : NotificationTriggers,
});
export const UserProfile = IDL.Record({
  'notificationPreferences' : IDL.Opt(NotificationPreferences),
  'name' : IDL.Text,
});
export const ArrivalStatus = IDL.Variant({
  'onTheWay' : IDL.Null,
  'atTheLake' : IDL.Null,
  'planning' : IDL.Null,
});
export const Camper = IDL.Record({
  'status' : ArrivalStatus,
  'siteNumber' : IDL.Opt(IDL.Text),
  'plannedArrival' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'plannedDeparture' : IDL.Opt(IDL.Int),
  'numberOfCampers' : IDL.Nat,
});
export const CampfireEvent = IDL.Record({
  'organizer' : IDL.Text,
  'campsiteNumber' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Int,
  'time' : IDL.Text,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const LakeLocationEvent = IDL.Record({
  'id' : IDL.Text,
  'organizer' : IDL.Text,
  'owner' : IDL.Principal,
  'time' : IDL.Text,
  'location' : LakeLocation,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addOrUpdateCamper' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCamper' : IDL.Func([IDL.Text], [], []),
  'createCampfireEvent' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createLakeLocationEvent' : IDL.Func(
      [IDL.Text, IDL.Text, LakeLocation],
      [],
      [],
    ),
  'deleteCampfireEvent' : IDL.Func([IDL.Int], [], []),
  'deleteLakeLocationEvent' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getCallerNotificationPreferences' : IDL.Func(
      [],
      [IDL.Opt(NotificationPreferences)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampers' : IDL.Func([], [IDL.Vec(Camper)], ['query']),
  'getCampfireEvents' : IDL.Func([], [IDL.Vec(CampfireEvent)], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getLakeLocationEvents' : IDL.Func(
      [],
      [IDL.Vec(LakeLocationEvent)],
      ['query'],
    ),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserNotificationPreferences' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(NotificationPreferences)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCallerNotificationPreferences' : IDL.Func(
      [NotificationPreferences],
      [],
      [],
    ),
  'updateCampfireEvent' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLakeLocationEvent' : IDL.Func(
      [IDL.Text, IDL.Text, LakeLocation],
      [],
      [],
    ),
  'updateNumberOfCampers' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updatePlannedDeparture' : IDL.Func([IDL.Text, IDL.Opt(IDL.Int)], [], []),
  'updateSiteNumber' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateStatus' : IDL.Func([IDL.Text, ArrivalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LakeLocation = IDL.Variant({
    'sandBar' : IDL.Null,
    'karenCove' : IDL.Null,
    'bigIslandBeach' : IDL.Null,
    'skylineBar' : IDL.Null,
    'marina' : IDL.Null,
    'bigIslandCove' : IDL.Null,
    'sandyBeach' : IDL.Null,
  });
  const ToastAppearance = IDL.Record({
    'animation' : IDL.Text,
    'style' : IDL.Text,
    'position' : IDL.Text,
  });
  const NotificationTriggers = IDL.Record({
    'departureWarning' : IDL.Bool,
    'messageReceived' : IDL.Bool,
    'campfireInvitation' : IDL.Bool,
    'lakeArrivalAlert' : IDL.Bool,
    'lakeLocationUpdate' : IDL.Bool,
    'eventReminder' : IDL.Bool,
  });
  const NotificationPreferences = IDL.Record({
    'appearance' : ToastAppearance,
    'triggers' : NotificationTriggers,
  });
  const UserProfile = IDL.Record({
    'notificationPreferences' : IDL.Opt(NotificationPreferences),
    'name' : IDL.Text,
  });
  const ArrivalStatus = IDL.Variant({
    'onTheWay' : IDL.Null,
    'atTheLake' : IDL.Null,
    'planning' : IDL.Null,
  });
  const Camper = IDL.Record({
    'status' : ArrivalStatus,
    'siteNumber' : IDL.Opt(IDL.Text),
    'plannedArrival' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'plannedDeparture' : IDL.Opt(IDL.Int),
    'numberOfCampers' : IDL.Nat,
  });
  const CampfireEvent = IDL.Record({
    'organizer' : IDL.Text,
    'campsiteNumber' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Int,
    'time' : IDL.Text,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const LakeLocationEvent = IDL.Record({
    'id' : IDL.Text,
    'organizer' : IDL.Text,
    'owner' : IDL.Principal,
    'time' : IDL.Text,
    'location' : LakeLocation,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addOrUpdateCamper' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCamper' : IDL.Func([IDL.Text], [], []),
    'createCampfireEvent' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createLakeLocationEvent' : IDL.Func(
        [IDL.Text, IDL.Text, LakeLocation],
        [],
        [],
      ),
    'deleteCampfireEvent' : IDL.Func([IDL.Int], [], []),
    'deleteLakeLocationEvent' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getCallerNotificationPreferences' : IDL.Func(
        [],
        [IDL.Opt(NotificationPreferences)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampers' : IDL.Func([], [IDL.Vec(Camper)], ['query']),
    'getCampfireEvents' : IDL.Func([], [IDL.Vec(CampfireEvent)], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getLakeLocationEvents' : IDL.Func(
        [],
        [IDL.Vec(LakeLocationEvent)],
        ['query'],
      ),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserNotificationPreferences' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(NotificationPreferences)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCallerNotificationPreferences' : IDL.Func(
        [NotificationPreferences],
        [],
        [],
      ),
    'updateCampfireEvent' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLakeLocationEvent' : IDL.Func(
        [IDL.Text, IDL.Text, LakeLocation],
        [],
        [],
      ),
    'updateNumberOfCampers' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updatePlannedDeparture' : IDL.Func([IDL.Text, IDL.Opt(IDL.Int)], [], []),
    'updateSiteNumber' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'updateStatus' : IDL.Func([IDL.Text, ArrivalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };